"""adadded model attribute


Revision ID: 2628718fc98f
Revises: 6abd7d318973
Create Date: 2018-04-20 07:48:32.372215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2628718fc98f'
down_revision = '6abd7d318973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lists', sa.Column('type_of_list', sa.String(length=28), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lists', 'type_of_list')
    # ### end Alembic commands ###
