"""added model

Revision ID: 6abd7d318973
Revises: c970b2852c4e
Create Date: 2018-04-20 07:28:37.199162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abd7d318973'
down_revision = 'c970b2852c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tried')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tried',
    sa.Column('strain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], name='tried_strain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tried_user_id_fkey')
    )
    # ### end Alembic commands ###
