"""another migration


Revision ID: c970b2852c4e
Revises: 
Create Date: 2018-04-20 05:52:56.029720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c970b2852c4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('strain_id', sa.Integer(), nullable=True))
    op.drop_constraint('search_results_strain.id_fkey', 'search_results', type_='foreignkey')
    op.create_foreign_key(None, 'search_results', 'strains', ['strain_id'], ['id'])
    op.drop_column('search_results', 'strain.id')
    op.add_column('searches', sa.Column('term', sa.String(length=64), nullable=True))
    op.drop_column('searches', 'query')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('query', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('searches', 'term')
    op.add_column('search_results', sa.Column('strain.id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'search_results', type_='foreignkey')
    op.create_foreign_key('search_results_strain.id_fkey', 'search_results', 'strains', ['strain.id'], ['id'])
    op.drop_column('search_results', 'strain_id')
    # ### end Alembic commands ###
